#mail
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nicholas4744@gmail.com
    password: mypjdkiiziyhgtkw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true